import "@/globals.css";
import type { Metadata } from "next";
import { auth } from "@/app/api/auth/[...nextauth]/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function PrivateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Antes de renderizar páginas nesse grupo de rotas, irei verificar
  // se o usuário está logado. Se não estiver, irei redirecionar para a página de login
  const session = await auth()

  if (!session) {
    console.log("não está logado");
    
    redirect("/login");
  }

  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}
